version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: endpoint do seu RDS
      WORDPRESS_DB_USER: seu master username (ex: admin)
      WORDPRESS_DB_PASSWORD: sua master password
      WORDPRESS_DB_NAME: nome do banco de dados (não o da instância RDS)
      WORDPRESS_TABLE_CONFIG: wp_